### ISSUE TITLE
Use `json_merger` as loader for webpack

### ISSUE THREAD

**Issue by kopach** [andlrc/json_merger#4]
I think it would be very handy to use this tool as loader for webpack.
for example:

```
        preLoaders: [
            {
                test: /\.json$/,
                loader: 'json_merger',
            }
        ],
```

So, it will be possible to generate .json from the pieces during the build.

But, webpack sends to the loader function only content and not path to the file.
So, how about to add one more public method (compile/generate/interpolate), which will take json, working context and will return the generated result.
for example:

```
var result = json_merger.compile(json, {
   context: __dirname + '/some/path';
});
```

**Comment by andlrc** [comment]
Thanks for your interest in json_merger. It's been some time since I last digged into the source code, but it seems like it should be quite easy to split `.fromFile` into two functions where one will suit your needs :smile:

I'm not gonna get the time to do anything this week, but feel free to make a pull request if you'd like.

**Comment by andlrc** [comment]
I have created `.fromObject` which takes the same arguments as `.fromFile`. This is WIP but I put it on the master branch since I don't think you can easily install another branch via `npm`. Please tell me if it helps you 😃

**Comment by kopach** [comment]
Great. Thanks a lot. I'll try it this week and let you know.

**Comment by kopach** [comment]
Tested - works just fine, thanks. Inspired by this, published my loader for webpack based on your plugin https://www.npmjs.com/package/json_merger-loader
