### ISSUE TITLE
Remove item from object / array

### ISSUE THREAD

**Issue by franciscolourenco** [andlrc/json_merger#7]
Is there a way to remove items from object or array?
Perhaps something along these lines:

animals.json
```json
{
  "animals": ["dog", "cat", "lion"]
}
```

pets.json
```json
{
  "@extends": "animals.json",
  "@subtract": ["animals"],
  "animals": ["tiger"]
}
```

json_merger pets.json
```json
{
  "animals": ["dog", "cat"]
}
```

**Comment by andlrc** [comment]
Take a look at [`@match`](https://github.com/andlrc/json_merger#match), you can use something like:

```
{
  "@extends": "animals.json",
  "animals": [
    {
      "@match": "[@value=lion]",
      "@delete": true
    }
  ]
}
```

I havn't tested it, but it seems like it would work 😄

**Comment by franciscolourenco** [comment]
Seems to be deleting the first item of the array.

manifest.json
```json
{
  "background": {
    "scripts": [
      "lib/mixpanel.js",
      "js/eventPage.js",
      "livereload.js"
    ],
    "persistent": true
  }
}
```

manifest-dist.json
```json
{
  "@extends": ["manifest.json"],
  "background": {
    "scripts": [{
      "@match": "@value=livereload.js",
      "@delete": true
    }],
    "persistent": false
  }
}
```

`$ json_merger manifest-dist.json --pretty`
```json
{
	"background": {
		"scripts": [
			"js/eventPage.js",
			"livereload.js"
		],
		"persistent": false
	}
}
```

**Comment by andlrc** [comment]
`"@match": "@value=livereload.js",` should be `"@match": "[@value=livereload.js]",`

**Comment by franciscolourenco** [comment]
hmm. the syntax doesn't make any sense to me at this point 😂 but it works. thanks

**Comment by andlrc** [comment]
You might be right, I was glancing over it twice just now, I think I derived `[@value=a]` from an attribute selector `[a=b]` combined with the `@value` indicator: https://github.com/andlrc/json_merger#value

**Comment by franciscolourenco** [comment]
I see. Have you considered supporting `"@delete": "[@value=livereload.js]"`?

**Comment by andlrc** [comment]
I think that might actually be supported, at least `@delete: "key"` in objects is, i.e:

    A = { "a": 1, "b": 2 }
    B = { "@delete": "a" }

Merging `B` onto `A` should result in:

    { "b": 2 }

**Comment by franciscolourenco** [comment]
```
{
  "@extends": ["manifest.json"],
  "background": {
    "scripts": [{
      "@delete": "[@value=livereload.js]"
    }],
    "persistent": false
  }
}

```
results in 
```json
	"background": {
		"scripts": [
			{},
			"src/js/eventPage.js",
			"livereload.js"
		],
		"persistent": false
	},
```
